// Generated by Molecule 0.5.0

#define MOLECULEC_VERSION 5000
#define MOLECULE_API_VERSION_MIN 5000

#include "molecule_reader_streaming.h"

#ifndef BLOCKCHAIN_H
#define BLOCKCHAIN_H

#ifdef __cplusplus
#define _CPP_BEGIN extern "C" {
#define _CPP_END }
_CPP_BEGIN
#endif /* __cplusplus */

#ifndef MOLECULE_API_DECORATOR
#define __DEFINE_MOLECULE_API_DECORATOR_BLOCKCHAIN
#define MOLECULE_API_DECORATOR
#endif /* MOLECULE_API_DECORATOR */

/*
 * Reader APIs
 */

struct Uint32_state {
    struct bytes_state state;
};
struct Uint32_callbacks { struct bytes_callbacks cb; };
struct Uint64_state {
    struct bytes_state state;
};
struct Uint64_callbacks { struct bytes_callbacks cb; };
struct Uint128_state {
    struct bytes_state state;
};
struct Uint128_callbacks { struct bytes_callbacks cb; };
struct Byte32_state {
    struct bytes_state state;
};
struct Byte32_callbacks { struct bytes_callbacks cb; };
struct Uint256_state {
    struct bytes_state state;
};
struct Uint256_callbacks { struct bytes_callbacks cb; };
struct Bytes_state {
    mol_num_t state_num;
    mol_num_t length;
    union { struct byte_state item; struct num_state num;} u;
};
struct Bytes_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*size)(mol_num_t);
    void (*body_chunk)(uint8_t*, mol_num_t);
};

MOLECULE_API_DECORATOR  void            MolReader_Bytes_init_state                      (struct Bytes_state *s, const struct Bytes_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    MOL_INIT_NUM();
}
struct BytesOpt_state {
    union { struct Bytes_state item; struct num_state num; } u;
};
struct BytesOpt_callbacks {
    void (*start)();
    void (*end)();
    void (*chunk)(uint8_t*, mol_num_t);
    const struct Bytes_callbacks *item;
};

struct BytesVec_state {
    mol_num_t state_num;
    mol_num_t field_idx;
    mol_num_t total_size;
    mol_num_t first_offset;
    union { struct Bytes_state item; struct num_state num;} u;
};
struct BytesVec_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*size)(mol_num_t);
    void (*length)(mol_num_t);
    void (*index)(mol_num_t);
    void (*offset)(mol_num_t);
    const struct Bytes_callbacks *item;
};

struct Byte32Vec_state {
    mol_num_t state_num;
    mol_num_t length;
    union { struct Byte32_state item; struct num_state num;} u;
};
struct Byte32Vec_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*size)(mol_num_t);
    void (*index)(mol_num_t);
    const struct Byte32_callbacks *item;
};

MOLECULE_API_DECORATOR  void            MolReader_Byte32Vec_init_state                  (struct Byte32Vec_state *s, const struct Byte32Vec_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    MOL_INIT_NUM();
}
struct Script_state {
    mol_num_t state_num;
    mol_num_t field_idx;
    mol_num_t total_size;
    mol_num_t code_hash_offset;
    mol_num_t hash_type_offset;
    mol_num_t args_offset;
    union {
        struct Byte32_state code_hash;
        struct byte_state hash_type;
        struct Bytes_state args;
        struct num_state num;
    } u;
};
struct Script_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*offsets)(struct Script_state*);
    const struct Byte32_callbacks *code_hash;
    const struct byte_callbacks *hash_type;
    const struct Bytes_callbacks *args;
};

struct ScriptOpt_state {
    union { struct Script_state item; struct num_state num; } u;
};
struct ScriptOpt_callbacks {
    void (*start)();
    void (*end)();
    void (*chunk)(uint8_t*, mol_num_t);
    const struct Script_callbacks *item;
};

struct OutPoint_state {
    mol_num_t state_num;
    union {
        struct Byte32_state tx_hash;
        struct Uint32_state index;
        struct num_state num;
    } u;
};
struct OutPoint_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    const struct Byte32_callbacks *tx_hash;
    const struct Uint32_callbacks *index;
};

struct CellInput_state {
    mol_num_t state_num;
    union {
        struct Uint64_state since;
        struct OutPoint_state previous_output;
        struct num_state num;
    } u;
};
struct CellInput_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    const struct Uint64_callbacks *since;
    const struct OutPoint_callbacks *previous_output;
};

struct CellInputVec_state {
    mol_num_t state_num;
    mol_num_t length;
    union { struct CellInput_state item; struct num_state num;} u;
};
struct CellInputVec_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*size)(mol_num_t);
    void (*index)(mol_num_t);
    const struct CellInput_callbacks *item;
};

MOLECULE_API_DECORATOR  void            MolReader_CellInputVec_init_state               (struct CellInputVec_state *s, const struct CellInputVec_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    MOL_INIT_NUM();
}
struct CellOutput_state {
    mol_num_t state_num;
    mol_num_t field_idx;
    mol_num_t total_size;
    mol_num_t capacity_offset;
    mol_num_t lock_offset;
    mol_num_t type__offset;
    union {
        struct Uint64_state capacity;
        struct Script_state lock;
        struct ScriptOpt_state type_;
        struct num_state num;
    } u;
};
struct CellOutput_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*offsets)(struct CellOutput_state*);
    const struct Uint64_callbacks *capacity;
    const struct Script_callbacks *lock;
    const struct ScriptOpt_callbacks *type_;
};

struct CellOutputVec_state {
    mol_num_t state_num;
    mol_num_t field_idx;
    mol_num_t total_size;
    mol_num_t first_offset;
    union { struct CellOutput_state item; struct num_state num;} u;
};
struct CellOutputVec_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*size)(mol_num_t);
    void (*length)(mol_num_t);
    void (*index)(mol_num_t);
    void (*offset)(mol_num_t);
    const struct CellOutput_callbacks *item;
};

struct CellDep_state {
    mol_num_t state_num;
    union {
        struct OutPoint_state out_point;
        struct byte_state dep_type;
        struct num_state num;
    } u;
};
struct CellDep_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    const struct OutPoint_callbacks *out_point;
    const struct byte_callbacks *dep_type;
};

struct CellDepVec_state {
    mol_num_t state_num;
    mol_num_t length;
    union { struct CellDep_state item; struct num_state num;} u;
};
struct CellDepVec_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*size)(mol_num_t);
    void (*index)(mol_num_t);
    const struct CellDep_callbacks *item;
};

MOLECULE_API_DECORATOR  void            MolReader_CellDepVec_init_state                 (struct CellDepVec_state *s, const struct CellDepVec_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    MOL_INIT_NUM();
}
struct RawTransaction_state {
    mol_num_t state_num;
    mol_num_t field_idx;
    mol_num_t total_size;
    mol_num_t version_offset;
    mol_num_t cell_deps_offset;
    mol_num_t header_deps_offset;
    mol_num_t inputs_offset;
    mol_num_t outputs_offset;
    mol_num_t outputs_data_offset;
    union {
        struct Uint32_state version;
        struct CellDepVec_state cell_deps;
        struct Byte32Vec_state header_deps;
        struct CellInputVec_state inputs;
        struct CellOutputVec_state outputs;
        struct BytesVec_state outputs_data;
        struct num_state num;
    } u;
};
struct RawTransaction_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*offsets)(struct RawTransaction_state*);
    const struct Uint32_callbacks *version;
    const struct CellDepVec_callbacks *cell_deps;
    const struct Byte32Vec_callbacks *header_deps;
    const struct CellInputVec_callbacks *inputs;
    const struct CellOutputVec_callbacks *outputs;
    const struct BytesVec_callbacks *outputs_data;
};

struct Transaction_state {
    mol_num_t state_num;
    mol_num_t field_idx;
    mol_num_t total_size;
    mol_num_t raw_offset;
    mol_num_t witnesses_offset;
    union {
        struct RawTransaction_state raw;
        struct BytesVec_state witnesses;
        struct num_state num;
    } u;
};
struct Transaction_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*offsets)(struct Transaction_state*);
    const struct RawTransaction_callbacks *raw;
    const struct BytesVec_callbacks *witnesses;
};

struct WitnessArgs_state {
    mol_num_t state_num;
    mol_num_t field_idx;
    mol_num_t total_size;
    mol_num_t lock_offset;
    mol_num_t input_type_offset;
    mol_num_t output_type_offset;
    union {
        struct BytesOpt_state lock;
        struct BytesOpt_state input_type;
        struct BytesOpt_state output_type;
        struct num_state num;
    } u;
};
struct WitnessArgs_callbacks {
    void (*start)();
    void (*chunk)(uint8_t*, mol_num_t);
    void (*end)();
    void (*offsets)(struct WitnessArgs_state*);
    const struct BytesOpt_callbacks *lock;
    const struct BytesOpt_callbacks *input_type;
    const struct BytesOpt_callbacks *output_type;
};

struct Uint32_state;
struct Uint32_callbacks;
typedef const struct Uint32_callbacks Uint32_cb;
MOLECULE_API_DECORATOR  void            MolReader_Uint32_init_state                     (struct Uint32_state *s, const struct Uint32_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_Uint32_parse                          (struct Uint32_state *s, struct mol_chunk *chunk, const struct Uint32_callbacks *cb, mol_num_t size);

struct Uint64_state;
struct Uint64_callbacks;
typedef const struct Uint64_callbacks Uint64_cb;
MOLECULE_API_DECORATOR  void            MolReader_Uint64_init_state                     (struct Uint64_state *s, const struct Uint64_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_Uint64_parse                          (struct Uint64_state *s, struct mol_chunk *chunk, const struct Uint64_callbacks *cb, mol_num_t size);

struct Uint128_state;
struct Uint128_callbacks;
typedef const struct Uint128_callbacks Uint128_cb;
MOLECULE_API_DECORATOR  void            MolReader_Uint128_init_state                    (struct Uint128_state *s, const struct Uint128_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_Uint128_parse                         (struct Uint128_state *s, struct mol_chunk *chunk, const struct Uint128_callbacks *cb, mol_num_t size);

struct Byte32_state;
struct Byte32_callbacks;
typedef const struct Byte32_callbacks Byte32_cb;
MOLECULE_API_DECORATOR  void            MolReader_Byte32_init_state                     (struct Byte32_state *s, const struct Byte32_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_Byte32_parse                          (struct Byte32_state *s, struct mol_chunk *chunk, const struct Byte32_callbacks *cb, mol_num_t size);

struct Uint256_state;
struct Uint256_callbacks;
typedef const struct Uint256_callbacks Uint256_cb;
MOLECULE_API_DECORATOR  void            MolReader_Uint256_init_state                    (struct Uint256_state *s, const struct Uint256_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_Uint256_parse                         (struct Uint256_state *s, struct mol_chunk *chunk, const struct Uint256_callbacks *cb, mol_num_t size);

struct Bytes_state;
struct Bytes_callbacks;
typedef const struct Bytes_callbacks Bytes_cb;
MOLECULE_API_DECORATOR  void            MolReader_Bytes_init_state                      (struct Bytes_state *s, const struct Bytes_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_Bytes_parse                           (struct Bytes_state *s, struct mol_chunk *chunk, const struct Bytes_callbacks *cb, mol_num_t size);

struct BytesOpt_state;
struct BytesOpt_callbacks;
typedef const struct BytesOpt_callbacks BytesOpt_cb;
MOLECULE_API_DECORATOR  void            MolReader_BytesOpt_init_state                   (struct BytesOpt_state *s, const struct BytesOpt_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_BytesOpt_parse                        (struct BytesOpt_state *s, struct mol_chunk *chunk, const struct BytesOpt_callbacks *cb, mol_num_t size);

struct BytesVec_state;
struct BytesVec_callbacks;
typedef const struct BytesVec_callbacks BytesVec_cb;
MOLECULE_API_DECORATOR  void            MolReader_BytesVec_init_state                   (struct BytesVec_state *s, const struct BytesVec_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_BytesVec_parse                        (struct BytesVec_state *s, struct mol_chunk *chunk, const struct BytesVec_callbacks *cb, mol_num_t size);

struct Byte32Vec_state;
struct Byte32Vec_callbacks;
typedef const struct Byte32Vec_callbacks Byte32Vec_cb;
MOLECULE_API_DECORATOR  void            MolReader_Byte32Vec_init_state                  (struct Byte32Vec_state *s, const struct Byte32Vec_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_Byte32Vec_parse                       (struct Byte32Vec_state *s, struct mol_chunk *chunk, const struct Byte32Vec_callbacks *cb, mol_num_t size);

struct Script_state;
struct Script_callbacks;
typedef const struct Script_callbacks Script_cb;
MOLECULE_API_DECORATOR  void            MolReader_Script_init_state                     (struct Script_state *s, const struct Script_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_Script_parse                          (struct Script_state *s, struct mol_chunk *chunk, const struct Script_callbacks *cb, mol_num_t size);

struct ScriptOpt_state;
struct ScriptOpt_callbacks;
typedef const struct ScriptOpt_callbacks ScriptOpt_cb;
MOLECULE_API_DECORATOR  void            MolReader_ScriptOpt_init_state                  (struct ScriptOpt_state *s, const struct ScriptOpt_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_ScriptOpt_parse                       (struct ScriptOpt_state *s, struct mol_chunk *chunk, const struct ScriptOpt_callbacks *cb, mol_num_t size);

struct OutPoint_state;
struct OutPoint_callbacks;
typedef const struct OutPoint_callbacks OutPoint_cb;
MOLECULE_API_DECORATOR  void            MolReader_OutPoint_init_state                   (struct OutPoint_state *s, const struct OutPoint_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_OutPoint_parse                        (struct OutPoint_state *s, struct mol_chunk *chunk, const struct OutPoint_callbacks *cb, mol_num_t size);

struct CellInput_state;
struct CellInput_callbacks;
typedef const struct CellInput_callbacks CellInput_cb;
MOLECULE_API_DECORATOR  void            MolReader_CellInput_init_state                  (struct CellInput_state *s, const struct CellInput_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_CellInput_parse                       (struct CellInput_state *s, struct mol_chunk *chunk, const struct CellInput_callbacks *cb, mol_num_t size);

struct CellInputVec_state;
struct CellInputVec_callbacks;
typedef const struct CellInputVec_callbacks CellInputVec_cb;
MOLECULE_API_DECORATOR  void            MolReader_CellInputVec_init_state               (struct CellInputVec_state *s, const struct CellInputVec_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_CellInputVec_parse                    (struct CellInputVec_state *s, struct mol_chunk *chunk, const struct CellInputVec_callbacks *cb, mol_num_t size);

struct CellOutput_state;
struct CellOutput_callbacks;
typedef const struct CellOutput_callbacks CellOutput_cb;
MOLECULE_API_DECORATOR  void            MolReader_CellOutput_init_state                 (struct CellOutput_state *s, const struct CellOutput_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_CellOutput_parse                      (struct CellOutput_state *s, struct mol_chunk *chunk, const struct CellOutput_callbacks *cb, mol_num_t size);

struct CellOutputVec_state;
struct CellOutputVec_callbacks;
typedef const struct CellOutputVec_callbacks CellOutputVec_cb;
MOLECULE_API_DECORATOR  void            MolReader_CellOutputVec_init_state              (struct CellOutputVec_state *s, const struct CellOutputVec_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_CellOutputVec_parse                   (struct CellOutputVec_state *s, struct mol_chunk *chunk, const struct CellOutputVec_callbacks *cb, mol_num_t size);

struct CellDep_state;
struct CellDep_callbacks;
typedef const struct CellDep_callbacks CellDep_cb;
MOLECULE_API_DECORATOR  void            MolReader_CellDep_init_state                    (struct CellDep_state *s, const struct CellDep_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_CellDep_parse                         (struct CellDep_state *s, struct mol_chunk *chunk, const struct CellDep_callbacks *cb, mol_num_t size);

struct CellDepVec_state;
struct CellDepVec_callbacks;
typedef const struct CellDepVec_callbacks CellDepVec_cb;
MOLECULE_API_DECORATOR  void            MolReader_CellDepVec_init_state                 (struct CellDepVec_state *s, const struct CellDepVec_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_CellDepVec_parse                      (struct CellDepVec_state *s, struct mol_chunk *chunk, const struct CellDepVec_callbacks *cb, mol_num_t size);

struct RawTransaction_state;
struct RawTransaction_callbacks;
typedef const struct RawTransaction_callbacks RawTransaction_cb;
MOLECULE_API_DECORATOR  void            MolReader_RawTransaction_init_state             (struct RawTransaction_state *s, const struct RawTransaction_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_RawTransaction_parse                  (struct RawTransaction_state *s, struct mol_chunk *chunk, const struct RawTransaction_callbacks *cb, mol_num_t size);

struct Transaction_state;
struct Transaction_callbacks;
typedef const struct Transaction_callbacks Transaction_cb;
MOLECULE_API_DECORATOR  void            MolReader_Transaction_init_state                (struct Transaction_state *s, const struct Transaction_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_Transaction_parse                     (struct Transaction_state *s, struct mol_chunk *chunk, const struct Transaction_callbacks *cb, mol_num_t size);

struct WitnessArgs_state;
struct WitnessArgs_callbacks;
typedef const struct WitnessArgs_callbacks WitnessArgs_cb;
MOLECULE_API_DECORATOR  void            MolReader_WitnessArgs_init_state                (struct WitnessArgs_state *s, const struct WitnessArgs_callbacks *cb);
MOLECULE_API_DECORATOR  mol_rv          MolReader_WitnessArgs_parse                     (struct WitnessArgs_state *s, struct mol_chunk *chunk, const struct WitnessArgs_callbacks *cb, mol_num_t size);


#undef ____

/*
 * Reader Functions
 */

#define                                 MolReader_Uint32_init_state(g, cbs)             mol_bytes_init_state(&(g->state), &((cbs)->cb))
#define                                 MolReader_Uint32_parse(g, c, cbs, sz)           mol_parse_bytes(&(g->state), c, &((cbs)->cb), 4)
#define                                 MolReader_Uint64_init_state(g, cbs)             mol_bytes_init_state(&(g->state), &((cbs)->cb))
#define                                 MolReader_Uint64_parse(g, c, cbs, sz)           mol_parse_bytes(&(g->state), c, &((cbs)->cb), 8)
#define                                 MolReader_Uint128_init_state(g, cbs)            mol_bytes_init_state(&(g->state), &((cbs)->cb))
#define                                 MolReader_Uint128_parse(g, c, cbs, sz)          mol_parse_bytes(&(g->state), c, &((cbs)->cb), 16)
#define                                 MolReader_Byte32_init_state(g, cbs)             mol_bytes_init_state(&(g->state), &((cbs)->cb))
#define                                 MolReader_Byte32_parse(g, c, cbs, sz)           mol_parse_bytes(&(g->state), c, &((cbs)->cb), 32)
#define                                 MolReader_Uint256_init_state(g, cbs)            mol_bytes_init_state(&(g->state), &((cbs)->cb))
#define                                 MolReader_Uint256_parse(g, c, cbs, sz)          mol_parse_bytes(&(g->state), c, &((cbs)->cb), 32)
MOLECULE_API_DECORATOR  mol_rv          MolReader_Bytes_parse                           (struct Bytes_state *s, struct mol_chunk *chunk, const struct Bytes_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    if(s->state_num == 0) {
        MOL_CALL_NUM(s->length);
        s->state_num++;
        if(size != MOL_NUM_MAX && (s->length * 1 + 4) != size) return REJECT;
        if(cb && cb->size) MOL_PIC(cb->size)(s->length * 1 + 4);
    }
    mol_num_t needed=s->length+1-s->state_num;
    mol_num_t available=chunk->length-chunk->consumed;
    mol_num_t copy=needed<available?needed:available;
    if(needed && cb && cb->body_chunk) MOL_PIC(cb->body_chunk)(chunk->ptr + chunk->consumed, copy);
    chunk->consumed+=copy;
    s->state_num+=copy;
    if(s->state_num-1 < s->length) return INCOMPLETE;
    DONE();
}
MOLECULE_API_DECORATOR  void            MolReader_BytesOpt_init_state                   (struct BytesOpt_state *s, const struct BytesOpt_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    MOL_INIT_SUBPARSER(item, Bytes);
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_BytesOpt_parse                        (struct BytesOpt_state *s, struct mol_chunk *chunk, const struct BytesOpt_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Option
    if(size==0) {
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
    }
    MOL_CALL_SUBPARSER(item, Bytes, size)
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}
MOLECULE_API_DECORATOR  void            MolReader_BytesVec_init_state                   (struct BytesVec_state *s, const struct BytesVec_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    s->field_idx=0;
    MOL_INIT_NUM();
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_BytesVec_parse                        (struct BytesVec_state *s, struct mol_chunk *chunk, const struct BytesVec_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // DynVec
    (void)(size); // FIXME: check sizes.
    switch(s->state_num) {
        case 0:
            MOL_CALL_NUM(s->total_size);
            MOL_INIT_NUM();
            if(cb && cb->size) MOL_PIC(cb->size)(s->total_size);
            if(s->total_size==4) {
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
            }
            if(size != MOL_NUM_MAX && size != s->total_size) return REJECT;
            s->state_num++;
        case 1:
            MOL_CALL_NUM(s->first_offset);
            MOL_INIT_NUM();
            s->field_idx=1;
            s->state_num++;
        case 2:
            while(s->field_idx < (s->first_offset>>2)-1) {
                mol_num_t scratch;
                MOL_CALL_NUM(scratch);
                MOL_INIT_NUM();
                s->field_idx++;
            }
            MOL_INIT_SUBPARSER(item, Bytes)
            s->field_idx=0;
            s->state_num++;
            if(cb && cb->length) MOL_PIC(cb->length)((s->first_offset>>2)-1);
            if(cb && cb->index) MOL_PIC(cb->index)(s->field_idx);
        case 3:
            while(s->field_idx < (s->first_offset>>2)-1) {
                MOL_CALL_SUBPARSER(item, Bytes, -1)
                MOL_INIT_SUBPARSER(item, Bytes)
                s->field_idx++;
                if(cb && cb->index) MOL_PIC(cb->index)(s->field_idx);
            }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}
MOLECULE_API_DECORATOR  mol_rv          MolReader_Byte32Vec_parse                       (struct Byte32Vec_state *s, struct mol_chunk *chunk, const struct Byte32Vec_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    if(s->state_num == 0) {
        MOL_CALL_NUM(s->length);
        s->state_num++;
        if(size != MOL_NUM_MAX && (s->length * 32 + 4) != size) return REJECT;
        if(cb && cb->size) MOL_PIC(cb->size)(s->length * 32 + 4);
        MOL_INIT_SUBPARSER(item, Byte32);
        if(cb && cb->index) MOL_PIC(cb->index)(s->state_num-1);
    }
    while(s->state_num-1 < s->length) {
        MOL_CALL_SUBPARSER(item, Byte32, 32);
        MOL_INIT_SUBPARSER(item, Byte32);
        s->state_num++;
        if(cb && cb->index) MOL_PIC(cb->index)(s->state_num-1);
    }
    DONE();
}
MOLECULE_API_DECORATOR  void            MolReader_Script_init_state                     (struct Script_state *s, const struct Script_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    s->field_idx=0;
    MOL_INIT_NUM();
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_Script_parse                          (struct Script_state *s, struct mol_chunk *chunk, const struct Script_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Table
    switch(s->state_num) {
        case 0:
            MOL_CALL_NUM(s->total_size);
            MOL_INIT_NUM();
            if(size!=MOL_NUM_MAX && s->total_size != size) return REJECT;
            s->state_num++;
        case 1:
            switch(s->field_idx) {
                case 0: {
                    MOL_CALL_NUM(s->code_hash_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 1: {
                    MOL_CALL_NUM(s->hash_type_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 2: {
                    MOL_CALL_NUM(s->args_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
            }
            s->state_num++;
            s->field_idx=0;
            MOL_INIT_SUBPARSER(code_hash, Byte32);
            if(cb && cb->offsets) MOL_PIC(cb->offsets)(s);
        case 2:
            switch(s->field_idx) {
            case 0: {
                MOL_CALL_SUBPARSER(code_hash, Byte32, s->hash_type_offset - s->code_hash_offset);
                MOL_INIT_SUBPARSER(hash_type, byte);
                s->field_idx++;
            }
            case 1: {
                MOL_CALL_SUBPARSER(hash_type, byte, s->args_offset - s->hash_type_offset);
                MOL_INIT_SUBPARSER(args, Bytes);
                s->field_idx++;
            }
            case 2: {
                MOL_CALL_SUBPARSER(args, Bytes, s->total_size-s->args_offset);
                s->state_num++;
            }
        }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}
MOLECULE_API_DECORATOR  void            MolReader_ScriptOpt_init_state                  (struct ScriptOpt_state *s, const struct ScriptOpt_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    MOL_INIT_SUBPARSER(item, Script);
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_ScriptOpt_parse                       (struct ScriptOpt_state *s, struct mol_chunk *chunk, const struct ScriptOpt_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Option
    if(size==0) {
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
    }
    MOL_CALL_SUBPARSER(item, Script, size)
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}
MOLECULE_API_DECORATOR  void            MolReader_OutPoint_init_state                   (struct OutPoint_state *s, const struct OutPoint_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    MOL_INIT_SUBPARSER(tx_hash, Byte32);
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_OutPoint_parse                        (struct OutPoint_state *s, struct mol_chunk *chunk, const struct OutPoint_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Struct
    if(size != 36 && size != MOL_NUM_MAX) return REJECT;
    switch(s->state_num) {
        case 0: {
            MOL_CALL_SUBPARSER(tx_hash, Byte32, 32)
            s->state_num++;
            MOL_INIT_SUBPARSER(index, Uint32)
        }
        case 1: {
            MOL_CALL_SUBPARSER(index, Uint32, 4)
        }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}

MOLECULE_API_DECORATOR  void            MolReader_CellInput_init_state                  (struct CellInput_state *s, const struct CellInput_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    MOL_INIT_SUBPARSER(since, Uint64);
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_CellInput_parse                       (struct CellInput_state *s, struct mol_chunk *chunk, const struct CellInput_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Struct
    if(size != 44 && size != MOL_NUM_MAX) return REJECT;
    switch(s->state_num) {
        case 0: {
            MOL_CALL_SUBPARSER(since, Uint64, 8)
            s->state_num++;
            MOL_INIT_SUBPARSER(previous_output, OutPoint)
        }
        case 1: {
            MOL_CALL_SUBPARSER(previous_output, OutPoint, 36)
        }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_CellInputVec_parse                    (struct CellInputVec_state *s, struct mol_chunk *chunk, const struct CellInputVec_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    if(s->state_num == 0) {
        MOL_CALL_NUM(s->length);
        s->state_num++;
        if(size != MOL_NUM_MAX && (s->length * 44 + 4) != size) return REJECT;
        if(cb && cb->size) MOL_PIC(cb->size)(s->length * 44 + 4);
        MOL_INIT_SUBPARSER(item, CellInput);
        if(cb && cb->index) MOL_PIC(cb->index)(s->state_num-1);
    }
    while(s->state_num-1 < s->length) {
        MOL_CALL_SUBPARSER(item, CellInput, 44);
        MOL_INIT_SUBPARSER(item, CellInput);
        s->state_num++;
        if(cb && cb->index) MOL_PIC(cb->index)(s->state_num-1);
    }
    DONE();
}
MOLECULE_API_DECORATOR  void            MolReader_CellOutput_init_state                 (struct CellOutput_state *s, const struct CellOutput_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    s->field_idx=0;
    MOL_INIT_NUM();
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_CellOutput_parse                      (struct CellOutput_state *s, struct mol_chunk *chunk, const struct CellOutput_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Table
    switch(s->state_num) {
        case 0:
            MOL_CALL_NUM(s->total_size);
            MOL_INIT_NUM();
            if(size!=MOL_NUM_MAX && s->total_size != size) return REJECT;
            s->state_num++;
        case 1:
            switch(s->field_idx) {
                case 0: {
                    MOL_CALL_NUM(s->capacity_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 1: {
                    MOL_CALL_NUM(s->lock_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 2: {
                    MOL_CALL_NUM(s->type__offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
            }
            s->state_num++;
            s->field_idx=0;
            MOL_INIT_SUBPARSER(capacity, Uint64);
            if(cb && cb->offsets) MOL_PIC(cb->offsets)(s);
        case 2:
            switch(s->field_idx) {
            case 0: {
                MOL_CALL_SUBPARSER(capacity, Uint64, s->lock_offset - s->capacity_offset);
                MOL_INIT_SUBPARSER(lock, Script);
                s->field_idx++;
            }
            case 1: {
                MOL_CALL_SUBPARSER(lock, Script, s->type__offset - s->lock_offset);
                MOL_INIT_SUBPARSER(type_, ScriptOpt);
                s->field_idx++;
            }
            case 2: {
                MOL_CALL_SUBPARSER(type_, ScriptOpt, s->total_size-s->type__offset);
                s->state_num++;
            }
        }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}
MOLECULE_API_DECORATOR  void            MolReader_CellOutputVec_init_state              (struct CellOutputVec_state *s, const struct CellOutputVec_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    s->field_idx=0;
    MOL_INIT_NUM();
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_CellOutputVec_parse                   (struct CellOutputVec_state *s, struct mol_chunk *chunk, const struct CellOutputVec_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // DynVec
    (void)(size); // FIXME: check sizes.
    switch(s->state_num) {
        case 0:
            MOL_CALL_NUM(s->total_size);
            MOL_INIT_NUM();
            if(cb && cb->size) MOL_PIC(cb->size)(s->total_size);
            if(s->total_size==4) {
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
            }
            if(size != MOL_NUM_MAX && size != s->total_size) return REJECT;
            s->state_num++;
        case 1:
            MOL_CALL_NUM(s->first_offset);
            MOL_INIT_NUM();
            s->field_idx=1;
            s->state_num++;
        case 2:
            while(s->field_idx < (s->first_offset>>2)-1) {
                mol_num_t scratch;
                MOL_CALL_NUM(scratch);
                MOL_INIT_NUM();
                s->field_idx++;
            }
            MOL_INIT_SUBPARSER(item, CellOutput)
            s->field_idx=0;
            s->state_num++;
            if(cb && cb->length) MOL_PIC(cb->length)((s->first_offset>>2)-1);
            if(cb && cb->index) MOL_PIC(cb->index)(s->field_idx);
        case 3:
            while(s->field_idx < (s->first_offset>>2)-1) {
                MOL_CALL_SUBPARSER(item, CellOutput, -1)
                MOL_INIT_SUBPARSER(item, CellOutput)
                s->field_idx++;
                if(cb && cb->index) MOL_PIC(cb->index)(s->field_idx);
            }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}
MOLECULE_API_DECORATOR  void            MolReader_CellDep_init_state                    (struct CellDep_state *s, const struct CellDep_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    MOL_INIT_SUBPARSER(out_point, OutPoint);
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_CellDep_parse                         (struct CellDep_state *s, struct mol_chunk *chunk, const struct CellDep_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Struct
    if(size != 37 && size != MOL_NUM_MAX) return REJECT;
    switch(s->state_num) {
        case 0: {
            MOL_CALL_SUBPARSER(out_point, OutPoint, 36)
            s->state_num++;
            MOL_INIT_SUBPARSER(dep_type, byte)
        }
        case 1: {
            MOL_CALL_SUBPARSER(dep_type, byte, 1)
        }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_CellDepVec_parse                      (struct CellDepVec_state *s, struct mol_chunk *chunk, const struct CellDepVec_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    if(s->state_num == 0) {
        MOL_CALL_NUM(s->length);
        s->state_num++;
        if(size != MOL_NUM_MAX && (s->length * 37 + 4) != size) return REJECT;
        if(cb && cb->size) MOL_PIC(cb->size)(s->length * 37 + 4);
        MOL_INIT_SUBPARSER(item, CellDep);
        if(cb && cb->index) MOL_PIC(cb->index)(s->state_num-1);
    }
    while(s->state_num-1 < s->length) {
        MOL_CALL_SUBPARSER(item, CellDep, 37);
        MOL_INIT_SUBPARSER(item, CellDep);
        s->state_num++;
        if(cb && cb->index) MOL_PIC(cb->index)(s->state_num-1);
    }
    DONE();
}
MOLECULE_API_DECORATOR  void            MolReader_RawTransaction_init_state             (struct RawTransaction_state *s, const struct RawTransaction_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    s->field_idx=0;
    MOL_INIT_NUM();
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_RawTransaction_parse                  (struct RawTransaction_state *s, struct mol_chunk *chunk, const struct RawTransaction_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Table
    switch(s->state_num) {
        case 0:
            MOL_CALL_NUM(s->total_size);
            MOL_INIT_NUM();
            if(size!=MOL_NUM_MAX && s->total_size != size) return REJECT;
            s->state_num++;
        case 1:
            switch(s->field_idx) {
                case 0: {
                    MOL_CALL_NUM(s->version_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 1: {
                    MOL_CALL_NUM(s->cell_deps_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 2: {
                    MOL_CALL_NUM(s->header_deps_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 3: {
                    MOL_CALL_NUM(s->inputs_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 4: {
                    MOL_CALL_NUM(s->outputs_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 5: {
                    MOL_CALL_NUM(s->outputs_data_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
            }
            s->state_num++;
            s->field_idx=0;
            MOL_INIT_SUBPARSER(version, Uint32);
            if(cb && cb->offsets) MOL_PIC(cb->offsets)(s);
        case 2:
            switch(s->field_idx) {
            case 0: {
                MOL_CALL_SUBPARSER(version, Uint32, s->cell_deps_offset - s->version_offset);
                MOL_INIT_SUBPARSER(cell_deps, CellDepVec);
                s->field_idx++;
            }
            case 1: {
                MOL_CALL_SUBPARSER(cell_deps, CellDepVec, s->header_deps_offset - s->cell_deps_offset);
                MOL_INIT_SUBPARSER(header_deps, Byte32Vec);
                s->field_idx++;
            }
            case 2: {
                MOL_CALL_SUBPARSER(header_deps, Byte32Vec, s->inputs_offset - s->header_deps_offset);
                MOL_INIT_SUBPARSER(inputs, CellInputVec);
                s->field_idx++;
            }
            case 3: {
                MOL_CALL_SUBPARSER(inputs, CellInputVec, s->outputs_offset - s->inputs_offset);
                MOL_INIT_SUBPARSER(outputs, CellOutputVec);
                s->field_idx++;
            }
            case 4: {
                MOL_CALL_SUBPARSER(outputs, CellOutputVec, s->outputs_data_offset - s->outputs_offset);
                MOL_INIT_SUBPARSER(outputs_data, BytesVec);
                s->field_idx++;
            }
            case 5: {
                MOL_CALL_SUBPARSER(outputs_data, BytesVec, s->total_size-s->outputs_data_offset);
                s->state_num++;
            }
        }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}
MOLECULE_API_DECORATOR  void            MolReader_Transaction_init_state                (struct Transaction_state *s, const struct Transaction_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    s->field_idx=0;
    MOL_INIT_NUM();
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_Transaction_parse                     (struct Transaction_state *s, struct mol_chunk *chunk, const struct Transaction_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Table
    switch(s->state_num) {
        case 0:
            MOL_CALL_NUM(s->total_size);
            MOL_INIT_NUM();
            if(size!=MOL_NUM_MAX && s->total_size != size) return REJECT;
            s->state_num++;
        case 1:
            switch(s->field_idx) {
                case 0: {
                    MOL_CALL_NUM(s->raw_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 1: {
                    MOL_CALL_NUM(s->witnesses_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
            }
            s->state_num++;
            s->field_idx=0;
            MOL_INIT_SUBPARSER(raw, RawTransaction);
            if(cb && cb->offsets) MOL_PIC(cb->offsets)(s);
        case 2:
            switch(s->field_idx) {
            case 0: {
                MOL_CALL_SUBPARSER(raw, RawTransaction, s->witnesses_offset - s->raw_offset);
                MOL_INIT_SUBPARSER(witnesses, BytesVec);
                s->field_idx++;
            }
            case 1: {
                MOL_CALL_SUBPARSER(witnesses, BytesVec, s->total_size-s->witnesses_offset);
                s->state_num++;
            }
        }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}
MOLECULE_API_DECORATOR  void            MolReader_WitnessArgs_init_state                (struct WitnessArgs_state *s, const struct WitnessArgs_callbacks *cb) {
    if(cb && cb->start) MOL_PIC(cb->start)();
    s->state_num=0;
    s->field_idx=0;
    MOL_INIT_NUM();
}

MOLECULE_API_DECORATOR  mol_rv          MolReader_WitnessArgs_parse                     (struct WitnessArgs_state *s, struct mol_chunk *chunk, const struct WitnessArgs_callbacks *cb, mol_num_t size) {
    mol_num_t start_idx = chunk->consumed;
    // Table
    switch(s->state_num) {
        case 0:
            MOL_CALL_NUM(s->total_size);
            MOL_INIT_NUM();
            if(size!=MOL_NUM_MAX && s->total_size != size) return REJECT;
            s->state_num++;
        case 1:
            switch(s->field_idx) {
                case 0: {
                    MOL_CALL_NUM(s->lock_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 1: {
                    MOL_CALL_NUM(s->input_type_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
                case 2: {
                    MOL_CALL_NUM(s->output_type_offset);
                    MOL_INIT_NUM();
                    s->field_idx++;
                }
            }
            s->state_num++;
            s->field_idx=0;
            MOL_INIT_SUBPARSER(lock, BytesOpt);
            if(cb && cb->offsets) MOL_PIC(cb->offsets)(s);
        case 2:
            switch(s->field_idx) {
            case 0: {
                MOL_CALL_SUBPARSER(lock, BytesOpt, s->input_type_offset - s->lock_offset);
                MOL_INIT_SUBPARSER(input_type, BytesOpt);
                s->field_idx++;
            }
            case 1: {
                MOL_CALL_SUBPARSER(input_type, BytesOpt, s->output_type_offset - s->input_type_offset);
                MOL_INIT_SUBPARSER(output_type, BytesOpt);
                s->field_idx++;
            }
            case 2: {
                MOL_CALL_SUBPARSER(output_type, BytesOpt, s->total_size-s->output_type_offset);
                s->state_num++;
            }
        }
    }
    if(cb && cb->chunk) MOL_PIC(cb->chunk)(chunk->ptr + start_idx, chunk->consumed - start_idx);
    if(cb && cb->end) MOL_PIC(cb->end)();
    return COMPLETE;
}

#ifdef __DEFINE_MOLECULE_API_DECORATOR_BLOCKCHAIN
#undef MOLECULE_API_DECORATOR
#undef __DEFINE_MOLECULE_API_DECORATOR_BLOCKCHAIN
#endif /* __DEFINE_MOLECULE_API_DECORATOR_BLOCKCHAIN */

#ifdef __cplusplus
_CPP_END
#undef _CPP_BEGIN
#undef _CPP_END
#endif /* __cplusplus */

#endif /* BLOCKCHAIN_H */
